language: php
sudo: false

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
matrix:
  fast_finish: true
  include:
    - php: nightly
    - env: COLLECT_COVERAGE=true
  allow_failures:
    - php: nightly
    - env: COLLECT_COVERAGE=true

before_install:
- travis_retry composer self-update

install:
- travis_retry composer install --no-interaction --prefer-source
- composer require php-coveralls/php-coveralls:^2 --dev

script:
- if [[ "$COLLECT_COVERAGE" == "true" ]]; then php vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml; else php vendor/phpunit/phpunit/phpunit; fi

after_script:
- if [[ "$COLLECT_COVERAGE" == "true" ]]; then php vendor/bin/php-coveralls; fi
