name: Code style

on:
  push:
  pull_request:

jobs:

  check-code-style:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']

    name: "Check code style | PHP ${{ matrix.php }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP with latest composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: none
          tools: none

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Check code style"
        run: composer run codestyle -- --dry-run
